[package]
name = "nmc"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
futures = "0.3.31"
indicatif = { version = "0.17.11", features = ["tokio"] }
tokio = { version = "1.44.1", features = ["full"] }
walkdir = "2.5.0"
